export const TELEGRAM_TEMPLATE_KEYS = {
  mainGigWithLink: 'mainGig.withLink',
  mainGigWithoutLink: 'mainGig.withoutLink',
  moderationGig: 'moderationGig',
  moderationLinkSeePost: 'moderation.link.seePost',
  moderationLinkOpenAdmin: 'moderation.link.openAdmin',
  gigTitleWithLink: 'gigTitle.withLink',
  gigTitleWithoutLink: 'gigTitle.withoutLink',
  weeklyDigestEmpty: 'weeklyDigest.empty',
  weeklyDigestHeader: 'weeklyDigest.header',
  weeklyDigestFooter: 'weeklyDigest.footer',
  weeklyDigestTicketsLabel: 'weeklyDigest.ticketsLabel',
  weeklyDigestTicketsLink: 'weeklyDigest.ticketsLink',
  weeklyDigestGigLineHtml: 'weeklyDigest.gigLine.html',
  weeklyDigestGigLinePlain: 'weeklyDigest.gigLine.plain',
  buttonApprove: 'button.approve',
  buttonEdit: 'button.edit',
  buttonHide: 'button.hide',
  buttonReject: 'button.reject',
  buttonPost: 'button.post',
  buttonShow: 'button.show',
  buttonSendToModeration: 'button.sendToModeration',
  buttonContactAdmins: 'button.contactAdmins',
  linkContactAdmins: 'link.contactAdmins',
  incomingMessageUnavailable: 'incomingMessage.unavailable',
  commandStart: 'command.start',
  commandUnknown: 'command.unknown',
  gigCandidateFeedbackSubmitted: 'gigCandidateFeedback.submitted',
  gigCandidateFeedbackAcceptedForModeration:
    'gigCandidateFeedback.acceptedForModeration',
  gigCandidateFeedbackRejected: 'gigCandidateFeedback.rejected',
  gigCandidateFeedbackAcceptedWithPublicLink:
    'gigCandidateFeedback.acceptedWithPublicLink',
  gigCandidateLinkOpenAdmin: 'gigCandidateLink.openAdmin',
  gigCandidateLinkSeeModerationPost: 'gigCandidateLink.seeModerationPost',
  gigLinkOpenAdmin: 'gigLink.openAdmin',
  gigLinkSeeMainPost: 'gigLink.seeMainPost',
} as const;

export type TelegramTemplateKey =
  (typeof TELEGRAM_TEMPLATE_KEYS)[keyof typeof TELEGRAM_TEMPLATE_KEYS];
